- name: Run PowerShell script that modifies the module changed result
  hosts: all
  win_shell:
    script: |
      if (Get-Service -Name test -ErrorAction SilentlyContinue) {
          Remove-Service -Name test
      }
      else {
          $Ansible.Changed = $false
      }
