---
- hosts: all
  tasks:
  
  - name: Run PowerShell script that modifies the module changed result
    win_shell: |
      write-output "This is my hell"
    register: result

  - name: Process win_shell output
    set_fact:
      vms: "{{ result2.stdout | from_json }}"
