- name: Run multi-lined shell commands
  hosts: all
  gather_facts: false
  tasks:
  - name: Run Powershell
    ansible.windows.win_shell: |
      $value = Test-Path -Path C:\temp
      if ($value) {
        Remove-Item -Path C:\temp -Force
      }
      New-Item -Path C:\temp -ItemType Directory
