---
- hosts: all 
  tasks:
  
  - name: Run powershell script
    win_shell: get-date
    
  - name: Run PS Script
    win_shell: C:\users\localadmin\Documents\windows-automox-troubleshooter-v0.1.9.ps1
