---
# This playbook tests the script module on Windows hosts

- name: Run powershell script
  hosts: all 
  gather_facts: false
  tasks:
    - name: Run powershell script
      ansible.windows.win_shell: |
        Write-Output "My hell"
